"""
reportHandler API

Behavior Overview:
-----------------
This Lambda manages report generation for individual jobs. Each job gets ONE unique report.
Reports are generated by triggering an external n8n workflow that processes preprocessed 
ad data (JSON and image2text extractions) and returns a comprehensive analysis report.

API Endpoint: https://<YOUR-AWS-API>/dev/jobs/{jobId}/report-status
Method: GET

API input:

{
    "pathParameters": {
        "jobId": str      # Unique job identifier
    }
}

All API output scenarios:

1. Report Generation Started (First Call)
   {
       "reportStatus": 1,
       "message": "Report generation in progress - please continue polling"
   }

2. Success - Report Already Exists  
   Status Code: 200  
   {
       "reportStatus": 2,
       "reportPath": str,       # Existing S3 key for the report
       "message": "Report already exists"
   }

3. Waiting - Scraper Not Complete  
   Status Code: 200  
   {
       "reportStatus": 0,
       "message": "Scraper not completed yet",
       "scraperStatus": int
   }

4. Waiting - Image2Text In Progress  
   {
       "reportStatus": 1,
       "message": "Waiting for image extraction to complete - please continue polling",
       "image2textStatus": 1
   }

5. Retrying - Workflow or Data Check  
   Status Code: 200  
   {
       "reportStatus": 0,
       "message": str,
       "retrying": true,
       "retryCount": int,           # Workflow retry count
       "dataCheckRetryCount": int   # Data availability retry count
   }

6. Completed - Empty or Successful Report  
   Status Code: 200  
   {
       "reportStatus": 2,
       "reportPath": str,         # S3 key of generated report (if any)
       "message": str
   }

7. Failed - Permanent or Fatal Error  
   Status Code: 200  
   {
       "reportStatus": -1,
       "message": str,
       "permanent": true,
       "retryCount": int
   }

8. Error - Internal or Database Failure  
   Status Code: 500  
   {
       "error": str,
       "message": str
   }

Key Points:
1. **One Report Per Job**: Once a report is generated for a job, it cannot be regenerated.
   - Enforced via `reportPath` field - if it exists, always return that report path.
   - No locking mechanism needed since each job has its own unique report.

2. **Strict Dependency Chain**:
   - Scraping must complete successfully (`scraperStatus = 2`) before report generation
   - If scraping failed (`scraperStatus = -1`), report inherits failure
   - If scraping in progress (`scraperStatus = 0 or 1`), report waits

3. **Smart Prerequisites Check**:
   - Check `scraperStatus` first - must be 2 (completed)
   - If `numAds = 0`: Generate empty report after 3 data-check retries
   - If `image2textStatus == 1`: Set `reportStatus = 1` and wait
   - If `image2textStatus == 0 or 2`: Check actual S3 data availability
     - If data exists → proceed with report generation
     - If no data after 3 retries → generate empty report

4. **Report Generation Flow**:
   - Check if report already exists → return existing reportPath (no URL)
   - Check scraping completed successfully
   - Check if image2text is in progress → set reportStatus=1 and return (for polling)
   - Check actual S3 data availability (not just folder existence)
   - If no data: retry up to 3 times, then generate empty report
   - Set reportStatus=1 before triggering workflow (for polling)
   - Trigger n8n workflow (synchronous call with timeout)
   - Save returned report JSON to S3 at `reports/{jobId}/report.json`
   - Update job with reportStatus=2 and reportPath
   - Return reportPath (fetchReport API will generate presigned URL)

5. **Retry Logic**:
   - Data unavailability: Max 3 retries, then generate empty report
   - N8N workflow failures: Max 5 retries on transient failures
   - On permanent failure: reportStatus = -1
   - Retry count reset to 0 on successful generation

6. **Status Values**:
   - reportStatus: 0 = idle, 1 = in progress, 2 = completed, -1 = permanently failed
   - scraperStatus: 0 = idle, 1 = in progress, 2 = completed, -1 = permanently failed
   - image2textStatus: 0 = not started, 1 = in progress, 2 = completed

"""

import os
import json
import boto3
import logging
from botocore.exceptions import ClientError
from datetime import datetime, timezone, timedelta
from decimal import Decimal

import requests

# -------------------------------
# Logging Setup
# -------------------------------
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# -------------------------------
# Environment Variables
# -------------------------------
BUCKET = os.environ.get("S3_BUCKET", "test-2-adspy")
JOBS_TABLE_NAME = os.environ.get("JOBS_TABLE", "jobs")
COMPANIES_TABLE_NAME = os.environ.get("COMPANIES_TABLE", "companies")
N8N_REPORT_WEBHOOK_URL = os.environ.get("N8N_REPORT_WEBHOOK_URL")
MAX_WORKFLOW_RETRIES = int(os.environ.get("MAX_WORKFLOW_RETRIES", "3"))
MAX_DATA_CHECK_RETRIES = int(os.environ.get("MAX_DATA_CHECK_RETRIES", "3"))
N8N_REQUEST_TIMEOUT = int(os.environ.get("N8N_REQUEST_TIMEOUT", "120"))  # 2 minutes

# -------------------------------
# AWS Clients
# -------------------------------
dynamodb = boto3.resource('dynamodb')
jobs_table = dynamodb.Table(JOBS_TABLE_NAME)
companies_table = dynamodb.Table(COMPANIES_TABLE_NAME)
s3 = boto3.client('s3')

# -------------------------------
# Utility Functions
# -------------------------------
def decimal_default(obj):
    """Convert Decimal to int for JSON serialization."""
    if isinstance(obj, Decimal):
        return int(obj)
    raise TypeError

def safe_name(s: str) -> str:
    """
    Convert company name into safe S3 folder name.
    Matches the naming convention used in scrape Lambda.
    """
    return "".join(c if c.isalnum() or c in (" ", ".", "_", "-") else "_" for c in s).replace(" ", "_").lower()

def parse_iso_date(date_str: str):
    """Safely parse ISO datetime string. Return None if invalid."""
    try:
        return datetime.fromisoformat(date_str)
    except (TypeError, ValueError):
        return None

def check_s3_folder_has_usable_data(prefix: str, check_json_content: bool = False) -> bool:
    """
    Check if S3 folder contains usable files.
    
    For JSON files: If check_json_content=True, also verify that JSON files
    contain actual data (not just empty "results": [] arrays).
    
    For image files: Just check existence.
    """
    try:
        response = s3.list_objects_v2(Bucket=BUCKET, Prefix=prefix, MaxKeys=100)
        
        if response.get('KeyCount', 0) == 0:
            return False
        
        # Get all file keys
        file_keys = [obj['Key'] for obj in response.get('Contents', []) 
                     if not obj['Key'].endswith('/')]  # Exclude folder markers
        
        if not file_keys:
            return False
        
        # If checking JSON content, verify at least one file has data
        if check_json_content:
            for key in file_keys:
                if key.endswith('.json'):
                    try:
                        obj = s3.get_object(Bucket=BUCKET, Key=key)
                        content = json.loads(obj['Body'].read().decode('utf-8'))
                        
                        # Check if content has actual data
                        # Common patterns: {"results": [...]} or direct array
                        if isinstance(content, dict):
                            results = content.get('results', [])
                            if results and len(results) > 0:
                                return True
                        elif isinstance(content, list) and len(content) > 0:
                            return True
                    except Exception as e:
                        logger.warning(f"[s3] Failed to read JSON file {key}: {e}")
                        continue
            
            # No JSON files with actual data found
            return False
        
        # For non-JSON checks (images), just verify files exist
        return True
        
    except Exception as e:
        logger.error(f"[s3] Error checking folder {prefix}: {e}")
        return False

def generate_empty_report(company_name: str, num_ads: int, reason: str) -> dict:
    """
    Generate an empty report when no data is available or company has no ads.
    
    Parameters:
    - company_name: str
    - num_ads: int
    - reason: str (explanation for why report is empty)
    
    Returns:
    - dict: Empty report structure
    """
    return {
        "companyName": company_name,
        "numAds": num_ads,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "reportType": "empty",
        "reason": reason,
        "summary": f"No analysis available: {reason}",
        "analysis": None,
        "recommendations": []
    }

# -------------------------------
# N8N Workflow Trigger
# -------------------------------
def trigger_report_workflow(company_id: str, company_name: str, job_id: str,
                           preprocessed_json_path: str, image2text_path: str) -> dict:
    """
    Trigger external n8n workflow to generate report.
    This is a FIRE-AND-FORGET call - triggers n8n workflow and returns immediately.
    The n8n workflow will update DynamoDB when report generation completes.
    
    Parameters:
    - company_id: str
    - company_name: str
    - job_id: str
    - preprocessed_json_path: S3 path to preprocessed JSON data
    - image2text_path: S3 path to image2text extraction data
    
    Returns:
    - bool: True if workflow was triggered successfully
    
    Raises:
    - ValueError: For permanent errors (invalid data, configuration issues)
    - Exception: For transient errors (timeouts, temporary network issues)
    """
    if not N8N_REPORT_WEBHOOK_URL:
        logger.error("[n8n] N8N_REPORT_WEBHOOK_URL not configured")
        raise ValueError("Permanent error: N8N report webhook URL not configured")
    
    payload = {
        "companyId": company_id,
        "companyName": safe_name(company_name),
        "jobId": job_id,
        "bucket": BUCKET,
        "preprocessedJsonPath": preprocessed_json_path,
        "image2textPath": image2text_path,
        "timestamp": datetime.now(timezone.utc).isoformat()
    }
    
    try:
        logger.info(f"[n8n] Triggering report workflow for job {job_id} (fire-and-forget)")
        
        response = requests.post(
            N8N_REPORT_WEBHOOK_URL,
            json=payload,
            timeout=5,  # Short timeout - just confirm trigger accepted
            headers={"Content-Type": "application/json"}
        )
        response.raise_for_status()
        
        logger.info(f"[n8n] Report workflow triggered successfully for job {job_id}")
        return True  # Just confirm trigger succeeded
        
    except requests.exceptions.Timeout:
        # Timeout is OK for fire-and-forget - webhook was triggered
        logger.info(f"[n8n] Webhook triggered for job {job_id} (timed out waiting for response, but that's expected)")
        return True

    except requests.exceptions.ConnectionError as e:
        logger.error(f"[n8n] Connection error: {e}")
        raise Exception("Transient error: Failed to connect to n8n workflow")

    except requests.exceptions.HTTPError as e:
        status_code = e.response.status_code if e.response else None
        # 4xx errors are typically permanent (bad request, unauthorized, etc.)
        if status_code and 400 <= status_code < 500:
            logger.error(f"[n8n] HTTP {status_code} error: {e}")
            raise ValueError(f"Permanent error: n8n workflow returned HTTP {status_code}")
        # 5xx errors are typically transient (server issues)
        else:
            logger.error(f"[n8n] HTTP error: {e}")
            raise Exception(f"Transient error: n8n workflow HTTP error")

    except ValueError:
        # Re-raise ValueError as-is (permanent errors)
        raise

    except Exception as e:
        logger.error(f"[n8n] Unexpected error triggering workflow: {e}")
        raise Exception(f"Transient error: {str(e)}")

# -------------------------------
# Lambda Handler
# -------------------------------
def lambda_handler(event, context):
    """
    Main Lambda handler for report generation.
    
    Expected API Gateway event format:
    - pathParameters: { "jobId": "..." }
    
    Response format:
    {
        "reportStatus": int,      # 0/1/2/-1
        "reportPath": str,        # S3 key (if status=2)
        "message": str,           # Status/error message (always present)
        "retryCount": int,        # Current retry count
        "dataCheckRetryCount": int, # Data availability retry count
        "permanent": bool,        # True if permanently failed
        "retrying": bool,         # True if will retry
        "scraperStatus": int,     # Prerequisite status
        "image2textStatus": int   # Prerequisite status (if relevant)
    }
    
    Note: No presigned URL generated here - use fetchReport API for that.
    """
    try:
        # =====================================
        # VALIDATION
        # =====================================
        job_id = event.get('pathParameters', {}).get('jobId')
        if not job_id or not isinstance(job_id, str) or not job_id.strip():
            logger.warning("[validation] Missing or invalid jobId")
            return {
                "statusCode": 400,
                "body": json.dumps({
                    "error": "Invalid or missing jobId",
                    "message": "jobId is required in path parameters"
                })
            }
        
        # Fetch job from DynamoDB
        try:
            response = jobs_table.get_item(Key={'jobId': job_id})
            job_item = response.get('Item')
        except Exception as e:
            logger.error(f"[dynamodb] Error fetching job {job_id}: {e}")
            return {
                "statusCode": 500,
                "body": json.dumps({
                    "error": "Database error fetching job",
                    "message": f"Failed to retrieve job {job_id} from database"
                })
            }
        
        if not job_item:
            logger.warning(f"[validation] Job not found: {job_id}")
            return {
                "statusCode": 404,
                "body": json.dumps({
                    "error": "Job not found",
                    "message": f"No job exists with ID {job_id}"
                })
            }
        
        company_id = job_item.get('companyId')
        if not company_id or not isinstance(company_id, str) or not company_id.strip():
            logger.error(f"[validation] Invalid companyId in job {job_id}")
            return {
                "statusCode": 400,
                "body": json.dumps({
                    "error": "Invalid companyId in job data",
                    "message": "Job data is corrupted - missing or invalid companyId"
                })
            }
        
        report_status = int(job_item.get('reportStatus', 0))
        report_path = job_item.get('reportPath', '').strip()
        scraper_status = int(job_item.get('scraperStatus', 0))
        image2text_status = int(job_item.get('image2textStatus', 0))
        
        # =====================================
        # GUARD: Report Already Exists
        # =====================================
        if report_path:
            logger.info(f"[guard] Report already exists for job {job_id}: {report_path}")
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "reportStatus": 2,
                    "reportPath": report_path,
                    "message": "Report already generated for this job"
                })
            }
        
        # =====================================
        # GUARD: Data Inconsistency Check
        # =====================================
        if report_status == 2 and not report_path:
            logger.error(f"[error] Job {job_id} has reportStatus=2 but no reportPath")
            return {
                "statusCode": 500,
                "body": json.dumps({
                    "error": "Data inconsistency",
                    "message": "Report marked as complete but no report file found in database"
                })
            }
        
        # =====================================
        # GUARD: Permanent Failure
        # =====================================
        if report_status == -1:
            logger.info(f"[guard] Job {job_id} permanently failed")
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "reportStatus": -1,
                    "message": "Report generation permanently failed",
                    "retryCount": int(job_item.get('reportRetryCount', 0)),
                    "permanent": True
                }, default=decimal_default)
            }
        
        # =====================================
        # GUARD: Check image2text Status
        # =====================================
        # Check if image2text failed or completed while we were waiting
        if report_status == 1:
            report_started_at = job_item.get('reportStartedAt')
            
            # Only reset if workflow hasn't been triggered yet
            if not report_started_at:
                if image2text_status == 2:
                    # Image2text completed - reset to allow report generation
                    logger.info(f"[guard] Image extraction completed, resetting reportStatus to 0 for job {job_id}")
                    try:
                        jobs_table.update_item(
                            Key={'jobId': job_id},
                            UpdateExpression="SET reportStatus = :status",
                            ExpressionAttributeValues={':status': 0}
                        )
                        report_status = 0  # Update local variable
                    except Exception as db_error:
                        logger.error(f"[dynamodb] Failed to reset reportStatus: {db_error}")
                
                elif image2text_status == -1:
                    # Image2text failed permanently
                    logger.info(f"[guard] Image extraction failed permanently for job {job_id}")
                    try:
                        jobs_table.update_item(
                            Key={'jobId': job_id},
                            UpdateExpression="SET reportStatus = :status",
                            ExpressionAttributeValues={':status': 0}
                        )
                        report_status = 0  # Reset to allow retry/empty report generation
                    except Exception as db_error:
                        logger.error(f"[dynamodb] Failed to reset reportStatus: {db_error}")
                
                elif image2text_status == 0:
                    # Image2text reset to 0 (likely failed) - reset report status
                    logger.info(f"[guard] Image extraction reset to 0 (likely failed) for job {job_id}")
                    try:
                        jobs_table.update_item(
                            Key={'jobId': job_id},
                            UpdateExpression="SET reportStatus = :status",
                            ExpressionAttributeValues={':status': 0}
                        )
                        report_status = 0  # Update local variable
                    except Exception as db_error:
                        logger.error(f"[dynamodb] Failed to reset reportStatus: {db_error}")
        
        # =====================================
        # GUARD: In Progress
        # =====================================
        if report_status == 1:
            logger.info(f"[guard] Report generation in progress for job {job_id}")
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "reportStatus": 1,
                    "message": "Report generation in progress - please continue polling"
                })
            }
        
        # =====================================
        # GUARD: Check Scraping Prerequisite
        # =====================================
        # Scraping must complete successfully before report generation
        if scraper_status == -1:
            # Scraping failed permanently - inherit failure
            logger.info(f"[guard] Scraping failed for job {job_id}, inheriting failure")
            try:
                jobs_table.update_item(
                    Key={'jobId': job_id},
                    UpdateExpression="SET reportStatus = :status",
                    ExpressionAttributeValues={':status': -1}
                )
            except Exception as db_error:
                logger.error(f"[dynamodb] Failed to set reportStatus=-1: {db_error}")
            
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "reportStatus": -1,
                    "message": "Cannot generate report - scraping failed permanently",
                    "scraperStatus": -1,
                    "permanent": True
                })
            }
        
        if scraper_status != 2:
            # Scraping not complete yet (status 0 or 1)
            logger.info(f"[guard] Scraping not complete for job {job_id} (status={scraper_status})")
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "reportStatus": 0,
                    "message": "Cannot generate report - scraping not complete yet (please wait for scraping to finish)",
                    "scraperStatus": scraper_status
                })
            }
        
        # At this point, scraper_status = 2 (scraping completed successfully)
        
        # =====================================
        # Fetch Company Data
        # =====================================
        try:
            company_response = companies_table.get_item(Key={'companyId': company_id})
            company_item = company_response.get('Item')
        except Exception as e:
            logger.error(f"[dynamodb] Error fetching company {company_id}: {e}")
            return {
                "statusCode": 500,
                "body": json.dumps({
                    "error": "Database error fetching company",
                    "message": f"Failed to retrieve company {company_id} from database"
                })
            }
        
        if not company_item:
            logger.error(f"[validation] Company not found: {company_id}")
            return {
                "statusCode": 404,
                "body": json.dumps({
                    "error": "Company not found",
                    "message": f"No company exists with ID {company_id}"
                })
            }
        
        company_name = company_item.get('companyName', '').strip().lower()
        safe_company = safe_name(company_name)
        num_ads = int(company_item.get('numAds', 0))
        
        # =====================================
        # Define S3 Paths
        # =====================================
        preprocessed_json_path = f"preprocessed/json/{safe_company}/"
        image2text_path = f"image2text/{safe_company}/"
        
        # =====================================
        # GUARD: Check image2text In Progress
        # =====================================
        # If image2text is in progress, set reportStatus=1 so UI continues polling
        if image2text_status == 1:
            # Only set reportStatus=1 if it's not already 1
            if report_status != 1:
                logger.info(f"[guard] Image extraction in progress for job {job_id}, setting reportStatus=1")
                try:
                    jobs_table.update_item(
                        Key={'jobId': job_id},
                        UpdateExpression="SET reportStatus = :status",
                        ExpressionAttributeValues={':status': 1}
                    )
                except Exception as db_error:
                    logger.error(f"[dynamodb] Failed to set reportStatus=1: {db_error}")
            
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "reportStatus": 1,
                    "message": "Waiting for image extraction to complete - please continue polling",
                    "image2textStatus": 1
                })
            }
        
        # =====================================
        # Check S3 Data Availability
        # =====================================
        has_usable_json = check_s3_folder_has_usable_data(preprocessed_json_path, check_json_content=True)
        has_image2text = check_s3_folder_has_usable_data(image2text_path, check_json_content=False)
        
        # =====================================
        # Handle No Data Scenario
        # =====================================
        if not has_usable_json and not has_image2text:
            # No usable data found - implement retry logic
            data_check_retry_count = int(job_item.get('dataCheckRetryCount', 0))
            
            logger.warning(f"[guard] No usable data for job {job_id} (attempt {data_check_retry_count + 1}/{MAX_DATA_CHECK_RETRIES})")
            
            if data_check_retry_count < MAX_DATA_CHECK_RETRIES:
                # Increment retry counter and return for next poll
                try:
                    jobs_table.update_item(
                        Key={'jobId': job_id},
                        UpdateExpression="SET dataCheckRetryCount = :rc",
                        ExpressionAttributeValues={':rc': data_check_retry_count + 1}
                    )
                except Exception as db_error:
                    logger.error(f"[dynamodb] Failed to increment dataCheckRetryCount: {db_error}")
                
                return {
                    "statusCode": 200,
                    "body": json.dumps({
                        "reportStatus": 0,
                        "message": f"Data not yet available - will retry (attempt {data_check_retry_count + 1}/{MAX_DATA_CHECK_RETRIES})",
                        "dataCheckRetryCount": data_check_retry_count + 1,
                        "retrying": True
                    }, default=decimal_default)
                }
            else:
                # Max data check retries exceeded - generate empty report
                logger.info(f"[empty_report] Generating empty report for job {job_id} after {data_check_retry_count} data check retries")
                
                reason = "No ad data available after scraping"
                if num_ads == 0:
                    reason = "Company has no ads"
                
                empty_report = generate_empty_report(company_name, num_ads, reason)
                
                # Save empty report to S3
                report_path = f"reports/{job_id}/report.json"
                try:
                    s3.put_object(
                        Bucket=BUCKET,
                        Key=report_path,
                        Body=json.dumps(empty_report, ensure_ascii=False, indent=2),
                        ContentType='application/json'
                    )
                    logger.info(f"[s3] Saved empty report to: {report_path}")
                except Exception as e:
                    logger.error(f"[s3] Failed to save empty report {report_path}: {e}")
                    return {
                        "statusCode": 500,
                        "body": json.dumps({
                            "error": "Failed to save empty report to S3",
                            "message": f"Empty report generation failed: {str(e)}"
                        })
                    }
                
                # Update job with completion
                try:
                    jobs_table.update_item(
                        Key={'jobId': job_id},
                        UpdateExpression="SET reportStatus = :status, reportPath = :path, dataCheckRetryCount = :rc",
                        ExpressionAttributeValues={
                            ':status': 2,
                            ':path': report_path,
                            ':rc': 0  # Reset retry count
                        }
                    )
                    logger.info(f"[complete] Empty report generated for job {job_id}")
                except Exception as e:
                    logger.error(f"[dynamodb] Failed to update job with empty report: {e}")
                    return {
                        "statusCode": 500,
                        "body": json.dumps({
                            "error": "Empty report generated but failed to update job status",
                            "message": f"Report saved to {report_path} but database update failed: {str(e)}",
                            "reportPath": report_path
                        })
                    }
                
                return {
                    "statusCode": 200,
                    "body": json.dumps({
                        "reportStatus": 2,
                        "reportPath": report_path,
                        "message": f"Empty report generated - {reason}"
                    })
                }
        
        # =====================================
        # Data Available - Proceed with Report Generation
        # =====================================
        logger.info(f"[check] Found usable data for job {job_id} (json={has_usable_json}, image2text={has_image2text})")
        
        # Reset data check retry count since we found data
        try:
            jobs_table.update_item(
                Key={'jobId': job_id},
                UpdateExpression="SET dataCheckRetryCount = :rc",
                ExpressionAttributeValues={':rc': 0}
            )
        except Exception as db_error:
            logger.error(f"[dynamodb] Failed to reset dataCheckRetryCount: {db_error}")
        
        # =====================================
        # Set Status to In Progress
        # =====================================
        now_iso = datetime.now(timezone.utc).isoformat()
        
        try:
            jobs_table.update_item(
                Key={'jobId': job_id},
                UpdateExpression="SET reportStatus = :status, reportStartedAt = :ts",
                ExpressionAttributeValues={':status': 1, ':ts': now_iso}
            )
            logger.info(f"[status] Set reportStatus=1 for job {job_id}")
        except Exception as e:
            logger.error(f"[dynamodb] Failed to set reportStatus=1: {e}")
            return {
                "statusCode": 500,
                "body": json.dumps({
                    "error": "Database error",
                    "message": "Failed to update job status before report generation"
                })
            }
        
        # =====================================
        # Trigger N8N Report Workflow
        # =====================================
        try:
            logger.info(f"[workflow] Triggering report generation for job {job_id}")
            trigger_report_workflow(
                company_id=company_id,
                company_name=company_name,
                job_id=job_id,
                preprocessed_json_path=preprocessed_json_path,
                image2text_path=image2text_path
            )
            
            # Workflow triggered successfully
            # n8n will update reportStatus, reportPath, and reset retry counts when done
            logger.info(f"[workflow] Report workflow triggered for job {job_id}, n8n will update status when complete")
            
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "reportStatus": 1,
                    "message": "Report generation started - please continue polling"
                })
            }
            
        except ValueError as e:
            # Permanent error - couldn't trigger workflow
            retry_count = int(job_item.get('reportRetryCount', 0))
            logger.error(f"[workflow] Permanent error triggering workflow for job {job_id}: {e}")
            
            try:
                jobs_table.update_item(
                    Key={'jobId': job_id},
                    UpdateExpression="SET reportStatus = :status, reportRetryCount = :rc",
                    ExpressionAttributeValues={':status': -1, ':rc': retry_count}
                )
            except Exception as db_error:
                logger.error(f"[dynamodb] Failed to update job status after permanent error: {db_error}")
            
            return {
                "statusCode": 200,
                "body": json.dumps({
                    "reportStatus": -1,
                    "message": f"Failed to trigger report generation: {str(e)}",
                    "permanent": True,
                    "retryCount": retry_count
                }, default=decimal_default)
            }
            
        except Exception as e:
            # Transient error - apply retry logic
            current_retry_count = int(job_item.get('reportRetryCount', 0))
            logger.error(f"[workflow] Transient error for job {job_id} (attempt {current_retry_count + 1}/{MAX_WORKFLOW_RETRIES}): {e}")
            
            if current_retry_count >= MAX_WORKFLOW_RETRIES:
                # Max retries exceeded - don't increment further
                try:
                    jobs_table.update_item(
                        Key={'jobId': job_id},
                        UpdateExpression="SET reportStatus = :status",
                        ExpressionAttributeValues={':status': -1}
                    )
                except Exception as db_error:
                    logger.error(f"[dynamodb] Failed to update job status after max retries: {db_error}")
                
                return {
                    "statusCode": 200,
                    "body": json.dumps({
                        "reportStatus": -1,
                        "message": f"Failed to trigger report generation after {MAX_WORKFLOW_RETRIES} attempts: {str(e)}",
                        "permanent": True,
                        "retryCount": current_retry_count
                    }, default=decimal_default)
                }
            else:
                # Still have retries left - increment and schedule retry
                new_retry_count = current_retry_count + 1
                logger.info(f"[workflow] Scheduling retry for job {job_id} (attempt {new_retry_count}/{MAX_WORKFLOW_RETRIES})")
                try:
                    jobs_table.update_item(
                        Key={'jobId': job_id},
                        UpdateExpression="SET reportStatus = :status, reportRetryCount = :rc",
                        ExpressionAttributeValues={':status': 0, ':rc': new_retry_count}
                    )
                except Exception as db_error:
                    logger.error(f"[dynamodb] Failed to reset job status for retry: {db_error}")
                
                return {
                    "statusCode": 200,
                    "body": json.dumps({
                        "reportStatus": 0,
                        "message": f"Failed to trigger report generation, will retry (attempt {new_retry_count}/{MAX_WORKFLOW_RETRIES}): {str(e)}",
                        "retrying": True,
                        "retryCount": new_retry_count
                    }, default=decimal_default)
                }
        
    except Exception as e:
        # Catch-all for unexpected errors
        logger.exception(f"[error] Unhandled exception in reportHandler: {e}")
        return {
            "statusCode": 500,
            "body": json.dumps({
                "error": "Internal server error",
                "message": f"Unexpected error occurred: {str(e)}"
            })
        }