"""
submitJobHandler API

Behavior Overview:
-----------------
This Lambda creates a new "job" in the DynamoDB `jobs` table for a specific company and session.
Each job represents a request to scrape data for a company.

API endpoint: https://<YOUR-AWS-API>/dev/jobs
Method: POST

API input body:
{
    "companyName": str,   # Name of the company to scrape
    "sessionUuid": str    # Unique session identifier for this job
}

All API output scenarios:
------------------------
1. Success - New Job Created:
    Status Code: 200
    Body: {
        "jobId": str,          # Unique job identifier
        "message": "New job created"
    }
2. Success - Job Already Exists:
    Status Code: 200
    Body: {
        "jobId": str,          # Existing job identifier
        "message": "Job already exists"
    }
3. Error - Missing Parameters:
    Status Code: 400
    Body: {
        "error": "companyName and sessionUuid are required"
    }
4. Error - Internal Server Error:
    Status Code: 500
    Body: {
        "error": str           # Error message
    }

Key Points:
1. Each job has a unique `jobId`, generated by hashing the combination of `companyName` and `sessionUuid`.
2. Jobs are associated with a `companyId`, which is a deterministic hash of the normalized company name.
    - This allows grouping multiple jobs targeting the same company.
    - Needed for the scraping logic to update all jobs when a scrape completes.
3. Fields added to support scraping logic:
    - `scraperStatus`: 0 = idle, 1 = in progress/polling, 2 = completed.
    - `scraperStartedAt`: timestamp when the job started scraping; used for stale checks.
    - `createdAt`: timestamp when the job was created; used to filter active jobs.
4. Existing fields:
    - `reportStatus`, `report`: for reporting purposes.
    - `reportStartedAt`: timestamp when report generation begins
    - `reportRetryCount`: number of retry attempts for report generation
5. If a job already exists for the same company/session, it returns the existing `jobId`.
6. The created job will be polled by the scraping Lambda to acquire locks and perform scraping.

Fields in DynamoDB `jobs` table after this Lambda runs:
- jobId (PK)
- companyId
- companyName
- sessionUuid
- createdAt
- scraperStatus
- scraperStartedAt
- reportStatus
- report
- scraperRetryCount
- image2textRetryCount
- reportRetryCount
- reportStartedAt: String (ISO timestamp),
- dataCheckRetryCount: Number

"""

import json
import hashlib
import os
import boto3
from datetime import datetime
from zoneinfo import ZoneInfo

# -------------------------------
# Initialize DynamoDB client
# -------------------------------
dynamodb = boto3.resource('dynamodb')
table_name = os.environ.get("JOBS_TABLE", "jobs")
table = dynamodb.Table(table_name)

# -------------------------------
# Utility Functions
# -------------------------------
def generate_company_id(company_name: str) -> str:
    """
    Generate deterministic companyId from normalized company name.
    This is used to group multiple jobs for the same company.
    """
    normalized = company_name.strip().lower()
    return hashlib.sha256(normalized.encode()).hexdigest()

# -------------------------------
# Lambda Handler
# -------------------------------
def lambda_handler(event, context):
    try:
        # --- Parse JSON body ---
        body = json.loads(event.get("body", "{}"))
        company_name = body.get("companyName")
        session_uuid = body.get("sessionUuid")
        
        # --- Validate required fields ---
        if not company_name or not company_name.strip() or not session_uuid or not session_uuid.strip():
            return {
                "statusCode": 400,
                "body": json.dumps({"error": "companyName and sessionUuid are required and cannot be empty"})
            }

        # --- Strip and normalize ---
        company_name = company_name.strip()
        session_uuid = session_uuid.strip()

        # --- Validate company name length ---
        MAX_COMPANY_NAME_LENGTH = 100
        if len(company_name) > MAX_COMPANY_NAME_LENGTH:
            return {
                "statusCode": 400,
                "body": json.dumps({"error": f"companyName exceeds maximum length of {MAX_COMPANY_NAME_LENGTH}"})
            }

        # --- Normalize for ID generation ---
        normalized_name = company_name.lower()
        
        # --- Generate jobId ---
        hash_input = f"{normalized_name}-{session_uuid}"
        job_id = hashlib.sha256(hash_input.encode()).hexdigest()
        
        # --- Generate companyId for grouping jobs ---
        company_id = hashlib.sha256(normalized_name.encode()).hexdigest()
        
        # --- Check if job already exists ---
        response = table.get_item(Key={"jobId": job_id})
        if "Item" in response:
            return {
                "statusCode": 200,
                "headers": {"Content-Type": "application/json"},
                "body": json.dumps({"jobId": job_id, "message": "Job already exists"})
            }
        
        # --- Get current timestamp ---
        created_at = datetime.now(ZoneInfo("America/Toronto")).isoformat()
        
        # --- Write new job to DynamoDB ---
        table.put_item(
            Item={
                "jobId": job_id,
                "companyId": company_id,
                "companyName": company_name,
                "sessionUuid": session_uuid,
                "createdAt": created_at,
                "scraperStatus": 0,
                "scraperStartedAt": None,
                "image2textStatus": 0,
                "reportStatus": 0,
                "reportPath": "",
                "scraperRetryCount": 0,
                "image2textRetryCount": 0,
                "reportRetryCount": 0,
                "reportStartedAt": None,
                "dataCheckRetryCount": 0
            }
        )
        
        # --- Return jobId to client ---
        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"jobId": job_id, "message": "New job created"})
        }
        
    except Exception as e:
        return {
            "statusCode": 500,
            "body": json.dumps({"error": str(e)})
        }
